# Generated by Django 4.2 on 2023-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0002_remove_provider_id_provider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inventory',
            field=models.IntegerField(default=10),
        ),
    ]
