# Generated by Django 4.2 on 2023-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0004_equipment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='imgsrc',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Empty_set_symbol.svg/640px-Empty_set_symbol.svg.png', max_length=10000),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
